from checkmate import checkmate

def main():

    print("--- Test 1: กระดาน 4x4 (King ปลอดภัย) ---")
    board_4x4 = """\
....
....
..K.
..P.\
"""
    checkmate(board_4x4)  

    print("\n--- Test 2: กระดาน 5x5 (โดน Bishop กินแนวทแยงมุม) ---")
    board_5x5 = """\
B....
.....
..K..
.....
....P\
"""
    checkmate(board_5x5)  

    print("\n--- Test 3: กระดาน 8x8 ไซส์มาตรฐาน (โดน Queen กินจากระยะไกล) ---")
    board_8x8 = """\
Q.......
........
........
........
........
........
........
.......K\
"""
    checkmate(board_8x8)  

    print("\n--- Test 4: กระดาน 8x8 (มีหมากบัง Queen ทำให้ King ปลอดภัย) ---")
    board_8x8_blocked = """\
Q.......
........
........
...P....
........
........
........
.......K\
"""
    checkmate(board_8x8_blocked)  

    print("\n--- Test 5: กระดาน 3x3 (โดน Pawn กิน) ---")
    board_3x3 = """\
...
.K.
P..\
"""
    checkmate(board_3x3)  

    print("\n--- Test 6: กระดานผิดปกติ 4x5 (เป็นสี่เหลี่ยมผืนผ้า) ---")
    board_invalid = """\
.....
.....
..K..
.....\
"""
    checkmate(board_invalid)  

    print("\n--- Test 7: กระดานผิดปกติ (มี King 2 ตัว) ---")
    board_two_kings = """\
K...
....
....
...K\
"""
    checkmate(board_two_kings)  

    print("\n--- Test 8: กระดานว่างเปล่า หรือรับค่าแปลกๆ ---")
    board_empty = ""
    checkmate(board_empty)  

if __name__ == "__main__":
    main()